### ISSUE TITLE
NuGet package missing Concordion.NUnit dll?

### ISSUE THREAD

**Issue by nigelcharman** [concordion/concordion.net#1]
Setting up a new project, I added the Concordion.NET NuGet package. 

When I try to run a Concordion test, I get the error:

> The target type doesn't contain tests from a known test framework or a 'Main' method.

Adding a reference to Concordion.NUnit.dll fixes this. 

Should Concordion.NUnit.dll be in the NuGet package?

**Comment by ShaKaRee** [comment]
It has to be declared in AssemblyInfo.cs that the spec projects needs the Concordion.NUnit addin to execute tests:
[assembly: RequiredAddin("ConcordionNUnitAddin")]

When Concordion.NUnit.dll is referenced from the spec project, it is loaded from the path. This is a feature of NUnit to debug addins.

**Comment by nigelcharman** [comment]
Thanks. On further investigation, I found that I had an old copy of Concordion.NUnit.dll in my NUnit addins folder.

I'll add an item to the FAQ to cover this.

**Comment by nigelcharman** [comment]
Done.
