### ISSUE TITLE
Latest NUnit (v 3.5)

### ISSUE THREAD

**Issue by philcarbone** [concordion/concordion.net#12]
Is there any reason this isn't utilizing the latest NUnit? 

Could it be upgraded?

**Comment by ShaKaRee** [comment]
Unfortunately the documentation on Custom Attributes for NUnit 3 is not available yet (https://github.com/nunit/docs/wiki/Custom-Attributes). With the help of Custom Attributes it would be possible to integrate Concordion.NET with NUnit 3.

In the meantime you can use the current existing integration of Concordion.NET with NUnit 2, which works for NUnit 3 as well.

Does this solve your problem?

**Comment by philcarbone** [comment]
Thank you. I've done this.
