### ISSUE TITLE
Data driven through Excel data

### ISSUE THREAD

**Issue by tmpalaniselvam** [concordion/concordion.net#16]
Hi Team,
 I'm looking for excel based data driven support from BDD tools. Do you provide the feature to utilize the excel data as parameterization?

Thanks,
Palani

**Comment by nigelcharman** [comment]
Hi Palani

For JVM-based Concordion we have the Excel Extension 
<https://github.com/concordion/concordion-excel-extension> which enables 
this. We don't currently have a corresponding extension for 
Concordion.NET, but believe that it should be possible to create one 
using the extension mechanism. Do let us know if you are keen to try 
creating one?

thanks
Nigel

**Comment by tmpalaniselvam** [comment]
Hi @nigelcharman ,
 Thanks for the info. Will close this issue.

Thanks.
